const teamProfile = [
  {
    id: 1,
    img: '/images/1.jpg',
    name: 'Sophie Adams',
    position: 'Software Engineer',
    phone: '+1 555-1234',
    email: 'sophie@example.com',
  },
  {
    id: 2,
    img: '/images/2.jpg',
    name: 'Liam Parker',
    position: 'Project Manager',
    phone: '+1 555-5678',
    email: 'liam@example.com',
  },
  {
    id: 3,
    img: '/images/3.jpg',
    name: 'Olivia Turner',
    position: 'Graphic Designer',
    phone: '+1 555-9876',
    email: 'olivia@example.com',
    website: 'oliviaturner.design',
  },
  {
    id: 4,
    img: '/images/4.jpg',
    name: 'Mason Foster',
    position: 'Marketing Specialist',
    phone: '+1 555-4321',
    email: 'mason@example.com',
  },
  {
    id: 5,
    img: '/images/5.jpg',
    name: 'Ava White',
    position: 'CEO',
    phone: '+1 555-8765',
    email: 'ava@example.com',
    website: 'avawhite.com',
  },
  {
    id: 6,
    img: '/images/6.jpg',
    name: 'Ethan Robinson',
    position: 'Frontend Developer',
    phone: '+1 555-3456',
    email: 'ethan@example.com',
    website: 'ethanrobinson.dev',
  },
];

export default teamProfile;
